# output dir will be created by hydra
data_dir: /srv/beegfs/scratch/groups/dpnc/atlas/ttbar_vflows/data/rel24_240209/hdf5/
output_dir: /home/users/l/leighm/scratch/Saved_Networks/

# Interpolated
root_dir: ${oc.env:PROJECT_ROOT}
full_path: ${paths.output_dir}/${project_name}/${network_name}/
